add guide: uuNotify
Uberspace/lab pull request #1062
Opened 2021-07-19 20:05 UTC by franok

guide for https://github.com/franok/uu-notify

followed the CONTRIBUTING.md and STYLE.md guidelines

closes #1058

2021-08-09 14:31 UTC, kimdiallo requested changes
Except for one small thing, the guide is so good. If you include the note there, I'll merge it that way.

2021-08-09 14:31 UTC, kimdiallo commented on source/guide_uu-notify.rst
> +Now add your `personal GitHub access token <https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token>`_. Example:
A hint that the token only needs access to the notifications would be appropriate here.

2021-08-09 16:36 UTC, franok commented
Thanks for the review. I'll be able to apply the suggested changes in approximately 4 weeks.

2021-08-11 07:23 UTC, nichtmax commented
@franok since this is just a small change, would you be fine with us adding the hint? If you want to do it by yourself we can of course wait 4 weeks ☺️

2021-08-11 07:41 UTC, franok commented
Yes, fine for me. Thanks :)

2021-08-12 05:39 UTC, merged

2021-08-12 05:42 UTC, nichtmax commented
Thanks for your guide! Check your mail for your cup 🎉