[castopod] Write guide to install castopod
Uberspace/lab pull request #1258
Opened 2022-05-05 16:36 UTC by Ryuno-Ki

This will close #1257.

I have some parts marked with TODO where I would need a hand.
Also I'm not sure whether I got the formatting right all the time.
It's my first guide :tea: 

Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>

2022-06-22 11:37 UTC, noave requested changes
Thanks :) I added some comments, there might be some more things to change afterwards, but lets start with these :-)

2022-06-22 11:37 UTC, noave commented on source/guide_castopod.rst
> +TODO: the permalink to latest version requires login:
that is bad, is it possible to get a link where you just need to lookup the latest version and replace it within the link?

2022-06-22 11:37 UTC, noave commented on source/guide_castopod.rst
> +  [isabell@stardust isabell]$ rm --force html/nocontent.html; rmdir html
no need for --force here

2022-06-22 11:37 UTC, noave commented on source/guide_castopod.rst
> +TODO: Codeblock needed here?
you should provide the full path to `.htaccess` and in a codeblock the lines that have to be removed (better comment with `#`) and then something like "edit the file with your editor and comment these lines out"

2022-06-22 11:37 UTC, noave commented on source/guide_castopod.rst
> +Before finishing the installation via wizard, set up some cronjobs for
please describe shortly how to edit cronjobs via `crontab -e`

2022-06-22 11:37 UTC, noave commented on source/guide_castopod.rst
> +You will see an error page. Add ``cp-install`` to the URL and finish the
just give the domain https://isabell.uber.space/cp-install and advise users to change it accordingly

2022-06-22 11:37 UTC, noave commented on source/guide_castopod.rst
> +After installation and updates, ensure that the file permissions are correct.
provide the code here to do this

2022-06-22 11:37 UTC, noave commented on source/guide_castopod.rst
> +TODO: Document how to run these without phpMyAdmin!
please also provide code for all moving files etc. :-)

2022-09-30 18:08 UTC, Ryuno-Ki commented
I waited so long that the Uberspace instance I used for setting it up (to verify my instructions) was disassembled by now.

2023-02-14 11:12 UTC, luto commented
Thanks for your guide! We would like to keep the list of open pull requests clean to improve the overview. Since this has been dormant for half a year, I'm closing this now. Once you find time to look at the comments, feel free to submit it again.

2023-02-14 11:12 UTC, closed without merging