Create guide_eturnal.rst
Uberspace/lab pull request #1300
Opened 2022-08-10 14:11 UTC by thisven

2022-08-24 12:12 UTC, noave requested changes
Thanks, I left some comments and will test the guide after fixing :) I am not sure if we should move the nextcloud and synapse parts to the regarding guides

2022-08-24 12:12 UTC, noave commented on source/guide_eturnal.rst
> +  * :manual:`cron jobs <daemons-cron>
links are broken, the last backtick is missing

2022-08-24 12:12 UTC, noave commented on source/guide_eturnal.rst
> +Check the `latest release`_ and download a precompiled tarball from https://eturnal.net:
please explicitly tell to adapt the url accordingly

2022-08-24 12:12 UTC, noave commented on source/guide_eturnal.rst
> +  [isabell@stardust ~]$ <super-long-secret>
remove the isabell@stardust part in this line

2022-08-24 12:12 UTC, noave commented on source/guide_eturnal.rst
> +.. code-block:: yaml
the code block is broken, you need to indent it, have a look at https://deploy-preview-1300--uberlab.netlify.app/guide_eturnal/

2022-08-24 12:12 UTC, noave commented on source/guide_eturnal.rst
> +As eturnal's startup procedure doesn't seem to work as supervisord_ program, it will be controlled using ``~/bin/eturnal`` bash script:
there is a _ after supervisord

2022-08-24 12:12 UTC, noave commented on source/guide_eturnal.rst
> +As eturnal's startup procedure doesn't seem to work as supervisord_ program, it will be controlled using ``~/bin/eturnal`` bash script:
please explicitly state to create this file with following content

2022-08-24 14:55 UTC, thisven commented
I've managed to add the logo to this PR. I think that's it. Have fun with testing. :smiley:

2022-09-13 12:30 UTC, nichtmax commented
Hey @thisven! Just a quick heads up, we haven't forgotten you. Noa is on vacation and will get back to you soon.

2022-11-30 09:18 UTC, thisven commented
I updated the guide as eturnal can be managed via supervisorctl if using foreground mode. Thanks to [Thomas](https://johnson.tj) for messaging me about that.

2023-02-15 11:18 UTC, merged

2023-02-15 11:23 UTC, luto commented
I added a couple small fixes. Thanks for the guide and sorry about the delay!