create guid_owncloud_infinite_scale.rst
Uberspace/lab pull request #1582
Opened 2023-09-02 14:30 UTC by pbielefeldt

basically taken from https://owncloud.com/news/hosting-infinite-scale-uberspace-ubernauten/

see #929

2023-09-03 10:11 UTC, EV21 requested changes
Hi 👋,

as a lab contributor I would like to give you some feedback. 

- ✔ Please rename the file so it starts with `guide_` (the `e` is missing) so the guide will be present in the preview and final deployment (link section)
  The current version ~~with the wrong link~~ can be found at [that location 👀](https://deploy-preview-1582--uberlab.netlify.app/guide_owncloud_infinite_scale/) 
- ⛔ Please just use the domain `isabell.uber.space` and no sub domains. The notice via `.. include:: includes/web-domain-list.rst` is usually enough the keep the guide short and users can simply follow the link to the manual.
- ✔ Please use the supervisor daemon (note: I used `~/bin/ocis` so the command works like this)
  ```rst
  Service Daemon
  --------------

  Create `~/etc/services.d/ocis.ini`

  .. code-block:: ini

    [program:ocis]
    environment=
      OCIS_URL="https://isabell.uber.space",
      PROXY_TLS="false",
      PROXY_HTTP_ADDR="0.0.0.0:9200",
      PROXY_LOG_LEVEL="warn"
    command=ocis server
    startsecs=30
    autostart=yes
    autorestart=yes

  .. include:: includes/supervisord.rst
  ```

- ✔❓ Move the part with the web backend further down after the service part (after starting the service) so there shouldn't be a `"NOT OK"` status
  This should be enough:
  ```rst
  .. note:: oCIS is running on port 9200.

  .. include:: includes/web-backend.rst
  ```

- ✔ I think `~/bin/ocis` is a better place to put the binary file (the config path defaults to `~/.ocis/config` so we don't need to worry about the working directory)
  ```console
  curl https://download.owncloud.com/ocis/ocis/stable/4.0.1/ocis-4.0.1-linux-amd64 --output ~/bin/ocis
  chmod +x ~/bin/ocis
  ocis init
  ```
- ❓ Maybe mention that all app related files and (encrypted) user files will be stored at `~/.ocis`
  ```console
  /home/isabell/.ocis
  |-- config
  |-- idm
  |-- idp
  |-- nats
  |-- search
  |-- storage
  `-- store
  ```

There are a few more things to do, but I leave that to the official reviewers.

2023-09-21 07:33 UTC, noave commented
@pbielefeldt thanks for starting the guide, do you want to take for those changes or should we take over here?

2023-10-06 14:30 UTC, pbielefeldt commented
> @pbielefeldt thanks for starting the guide, do you want to take for those changes or should we take over here?

@noave Thanks for asking.
Currently, I don't have the capacity myself to push this forward.
I also noticed that with this guide, the installation will be pretty unstable; this might need more investigation anyway (and more knowledge about ownCloud InfintScale than I currently have).

Hence, if there's someone who wants to and can continue on working on this guide, that would be great!

(Also: I can't compile the repo and I have no knowledge about the markup language used here, so that's an additional issue :-) ...)

2024-10-10 07:30 UTC, nichtmax commented
Any news here? If there's no feedback we'll close the PR, I'm not sure if it's a good idea to keep working on it, it's been a year now.

2024-10-10 14:52 UTC, EV21 commented
> Any news here? If there's no feedback we'll close the PR, I'm not sure if it's a good idea to keep working on it, it's been a year now.

Most change requests where already addressed in the last commit. - I just marked the bullet points in my review with symbols ✔⛔❓.

a few things I noted for the current state:
- The current oCIS version is 5.0.x (6.5.0 from last week currently has no documatation), so the used version in the PR is outdated.
- Ihe `Init` (config) section needs to be placed before the `Service Daemon` section.
- The `Run Server` section is obsolete since we have the `Service Deamon`
- Don't use subdomains like `myowncloud.isabell.uber.space`, only use `isabell.uber.space`
- Rename `Port Forwarding` to something like `Configure web backend` and simplify/rewrite the content like suggeted.
- The last 3 paragraphs of the last section may have their own section like `Access`
- `Tested with` is missing
- `.. author_list::` is missing at the end

**But all in all if the author or you don't want to work, test and finish this guide I also think this should be closed. Someone can still fork this work and go for a new PR.**

2024-10-20 15:37 UTC, pbielefeldt commented
Hi! As I mentioned, I don't have the capacity to work on this right now. Also, I do no longer have any Uberspace to try out. I did not get OCIS run really stable and reliably. I would love to see someone developing a working setup, and I am more than willing to contribute testing, feedback, and so forth. But for now, I think I can not be of great help here, sorry.

Feel free to use this as a starting point for a working guide though. Cheers!

2025-07-16 15:27 UTC, closed without merging