add initial MediaWiki guide
Uberspace/lab pull request #1758
Opened 2024-05-05 21:33 UTC by DougInAMug

This is an initial draft for a MediaWiki installation. I see now the contributing guidelines suggest opening an issue first... sorry I didn't do that.

I wrote it as I puzzled my way through, but then went through from the beginning again to check it all worked.

Advanced configuration, updates and backups not included.

2024-05-29 11:17 UTC, nichtmax requested changes
Thanks for the guide! Just a few things:

* Several links are broken in your preview, check out https://deploy-preview-1758--uberlab.netlify.app/guide_mediawiki/
* Please install directly into the DocumentRoot, not into https://<UberspaceUsername>.uber.space/mediawiki-1.41.1

2024-06-01 15:59 UTC, DougInAMug commented
@nichtmax I corrected one broken link, but couldn't see any others! What am I missing? :see_no_evil: 

I don't understand your second point. The guide asked users to change into the document root, and install to there.

2024-06-18 08:05 UTC, nichtmax requested changes
I can't edit your commit directly, otherwise I would have made the small changes by myself ☺️ 
With installation into the document root we mean no `/mediawiki-1.41.1` in the URL.

2024-06-18 08:05 UTC, nichtmax commented on source/guide_mediawiki.rst
> +  [isabell@stardust html]$ tar -xzvf mediawiki-*.tar.gz
Please add `--strip-components=1` to your tar command, then the installation will be in the document root without any sub folder like `/mediawiki-1.41.1`.

2024-06-18 08:05 UTC, nichtmax commented on source/guide_mediawiki.rst
> +At this point, the wiki installer should be available at ``https://<UberspaceUsername>.uber.space/mediawiki-1.41.1/``, click *"complete the installation"* to start the graphical `configuration <https
Please remove `mediawiki-1.41.1`.

2024-06-18 08:05 UTC, nichtmax commented on source/guide_mediawiki.rst
> +When the graphical installation completes, locally download the ``LocalSettings.php`` that should have been automatically generated and transfer it to ``~/html/mediawiki-1.41.1`` on your Uberspace. T
Please remove `mediawiki-1.41.1`.

2024-06-18 08:05 UTC, nichtmax commented on source/guide_mediawiki.rst
> +After this, the installed wiki should be available under ``https://<UberspaceUsername>.uber.space/mediawiki-1.41.1``
Please remove `mediawiki-1.41.1`.

2024-07-02 09:39 UTC, DougInAMug commented
Hey @nichtmax I hope that's OK now!

2024-07-02 14:24 UTC, merged