Add guide for umami
Uberspace/lab pull request #738
Opened 2020-08-19 16:33 UTC by thomas-kammerer

Umami is a simple, easy to use, self-hosted web analytics solution.
https://umami.is/

2020-08-30 20:08 UTC, luto requested changes
nicely done! I added a few comments, most of which you can fix by accepting the suggested change. Let me know what you think! :)

2020-08-30 20:08 UTC, luto commented on source/guide_umami.rst
> +For more information check the umami_ documentation.
Please add the default username/password as well as a warning box to change it immediately somewhere in the guide. I was kind of lost at the unexpected login screen :sweat_smile:

2020-08-30 21:02 UTC, thomas-kammerer commented
Thanks, I made the changes accordingly to your comments :)

2020-08-30 22:04 UTC, luto commented on source/guide_umami.rst
> +DATABASE_URL=mysql://isabell:mypassword@localhost:3306/umami
the new `isabell_umami:mypassword@localhost:3306/umami` changed the username to `isabell_umami`, not the database name.

2020-08-31 11:11 UTC, luto commented
thank you! :)

2020-08-31 11:11 UTC, merged