[Shiori] Add Shiori install guide
Uberspace/lab pull request #838
Opened 2020-11-12 05:36 UTC by Systemsemaphore

Hello all,
I need help with this guide before #837 can be closed.

I've written guide_shiori.rst (my first guide) based on guide_gotify.rst. I have successfully tested

- [x] installation

- [x] configuration (setting up a daemon)

- [x] accessing the web-ui and logging in

- [x] creating a new account

- [x] creating a bookmark

- [ ] However, I didn't manage to get it up and running behind a sub path

It's working with [https://shiori.uber.space](https://shiori.uber.space) and `uberspace web backend set / --http --port 8080` right now. I've tried `uberspace web backend set /shiori/ --http --port 8080` with and without `--remove-prefix` before, both fail with error 404. Help would be appreciated.

2020-11-12 17:16 UTC, Systemsemaphore commented
go-shiori/shiori#39

Awkward. I'll go fix _Prerequisites_

![bart](https://user-images.githubusercontent.com/74195074/98972740-2167f700-2513-11eb-966d-b1dc6febfd08.png)

2020-11-16 17:52 UTC, luto commented
Thank you! I'll take a look this week :)

2020-11-20 18:03 UTC, luto requested changes
Awesome! :tada: The guide works great :) I left a couple of suggestions to make it even more streamlined. Most of them can be applied by just pressing the commit button in the github web interface. Let me know what you think!

2020-11-20 18:03 UTC, luto commented on source/guide_shiori.rst
> +  [isabell@stardust ~]$ mkdir ~/shiori && cd ~/shiori
The app writes all data to `~/.local/share/shiori` and there aren't any configuration files. What do you think about saving the binary as `~/bin/shiori` using `wget ... -O ~/bin/shiori` and skipping the directory step entirely?

2020-11-20 18:03 UTC, luto commented on source/guide_shiori.rst
> +  command=/home/isabell/shiori/shiori-linux-amd64-stretch serve
if you move the binary to `~/bin/shiroi`, shorten this to
```suggestion
  command=shiori serve
```

2020-11-20 20:26 UTC, Systemsemaphore commented
Saving the binary as `~/bin/shiori` using `wget ... -O ~/bin/shiori` worked. Had to reconfigure the service as well but it's up and running again on my test account. I've added the suggested lines and looking at the preview right now I think there aren't any unresolved suggestions left. Please have another look, thanks in advance. In theory, it should also be possible to setup a backend for a specific domain and use the Document Root for something else besides Shiori but 1. [it's not encouraged](https://blog.uberspace.de/die-sache-mit-den-virtuellen-documentroots/) and 2. [it's against the rules for guides](https://github.com/Uberspace/lab/blob/master/STYLE.md) so I guess this will be an experiment just for me :)

2020-11-22 17:37 UTC, merged

2020-11-22 17:38 UTC, luto commented
Thank youu! :tada:

2020-11-22 17:40 UTC, luto commented
I can't find an email address on your github profile. Please ping hallo@uberspace.de about your reward :)