[firefly-iii] add guide for firefly iii
Uberspace/lab pull request #884
Opened 2020-12-16 19:37 UTC by FelixKohlen

This is a guide to install Firefly III on uberspace. Feedback is appreciated, as this is my first time contributing to this project.

Fixes #626

2020-12-16 20:50 UTC, Systemsemaphore commented
I was almost done with my guide for firefly-iii, was planning on uploading this weekend. Welp, guess I can delete that file now 😅 
Awesome work nonetheless! Thank you! 👍

2020-12-18 22:16 UTC, luto commented
Thanks for you submission! I'm sorry, but I won't find time to review it until mid-January :/

2021-01-13 16:20 UTC, luto requested changes
Thanks for the guide! There seems to be a bit of confusion about the working directory in the prompt. Can you have another look, please? Once that is resolved, I'll take your guide for a spin :)

2021-01-13 16:20 UTC, luto commented on source/guide_firefly-iii.rst
> + [isabell@stardust ~]$
the new working directory changes the prompt
```suggestion
 [isabell@stardust firefly_iii]$
```

2021-01-13 16:20 UTC, luto commented on source/guide_firefly-iii.rst
> + [isabell@stardust ~]$
the new working directory changes the prompt :)

```suggestion
 [isabell@stardust firefly_iii]$ php artisan migrate:refresh --seed
 [isabell@stardust firefly_iii]$ php artisan firefly-iii:upgrade-database
 [isabell@stardust firefly_iii]$ php artisan passport:install
 [isabell@stardust firefly_iii]$
```

2021-01-13 16:20 UTC, luto commented on source/guide_firefly-iii.rst
> + [isabell@stardust ~]$ composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-updated <next_version>
the new working directory changes the prompt :)

```suggestion
 [isabell@stardust isabell]$ composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-updated <next_version>
```

2021-01-13 16:20 UTC, luto commented on source/guide_firefly-iii.rst
> + [isabell@stardust ~]$ rm -rf bootstrap/cache/*
working directory, like above.

2021-01-13 16:20 UTC, luto commented on source/guide_firefly-iii.rst
> + [isabell@stardust ~]$ mv firefly_iii firefly-iii-old
working directory, like above.

2021-01-13 16:20 UTC, luto commented on source/guide_firefly-iii.rst
> +``MAIL_USERNAME`` and ``MAIL_PASSWORD`` must be the login data from a valid mail account.
Please include steps on how to create the required account.

2021-01-14 20:09 UTC, FelixKohlen commented
Sorry for the mess with the home directory, I completely forgot to change it while copy&pasting. Have a look at my changes, I think all your remarks should be addressed.

2021-01-18 19:03 UTC, FelixKohlen commented
@madmooose Did you install it on a fresh uberspace and did you follow the steps to change the DocumentRoot? I tested the guide again on a clean installation to make all the changes luto requested and I did not have to change the .htaccess file on that run.
I know I had .htaccess problems on my first try when I did not symlink the DocumentRoot to the firefly/public directory.

2021-01-18 19:42 UTC, madmooose commented
This could be the difference. I did the setup on my existing uberspace and used a subdomain. just saw that you need the rewritebase rule just for different documentroot (see here: https://manual.uberspace.de/web-documentroot/) . Maybe it's a good idea to mention it anyway here again. Just in case somebodys doing like i do (what of course is not recommended :) )

2021-01-20 19:27 UTC, merged

2021-01-20 19:27 UTC, luto commented
thank you! :tada:

2021-01-20 19:28 UTC, luto commented
@FelixKohlen I can't find your mail address. Please ping hallo@uberspace.de about your reward :)