Create guide_laravel.rst
Uberspace/lab pull request #921
Opened 2021-01-30 16:21 UTC by afriesinger

Guide for getting Laravel on uberspace to run. Cost me 2 day to figure it out...

2021-02-01 15:06 UTC, luto requested changes
Thanks for the submission! There are some oversights, so I don't think the guide would actually work like this. Once these are resolved, I'll have another look and take it for a spin.

2021-02-01 15:06 UTC, luto commented on source/guide_laravel.rst
> +Tested with Laravel 8 , Uberspace 7.2.1.0
Uberspace 7.2.1 was releases mid-2019. I doubt that you used this version to test your guide.

2021-02-01 15:06 UTC, luto commented on source/guide_laravel.rst
> +Adjust the .htaccess file
The code blocks in this section don't seem to render correctly. Do you mind having another look? https://deploy-preview-921--uberlab.netlify.app/guide_laravel.html#adjust-the-htaccess-file

2021-02-01 15:06 UTC, luto commented on source/guide_laravel.rst
> +Set Database up
The code blocks in this section don't seem to render correctly. Do you mind having another look? https://deploy-preview-921--uberlab.netlify.app/guide_laravel.html#set-database-up

2021-02-01 15:06 UTC, luto commented on source/guide_laravel.rst
> + [isabell@stardust html]$ composer global require "laravel/installer"
The prompt for this and the following lines should read `[isabell@stardust isabell]$` since we are in `/var/www/virtual/isabell/`.

2021-02-01 15:06 UTC, luto commented on source/guide_laravel.rst
> + [isabell@stardust ~]$ mv html/ htmlbackup/
`~/html` is just a symlink, moving it does not do anything. Are you sure the prompt should specify `~` as the working directory here?

2021-02-02 16:19 UTC, afriesinger commented
Hi Ubernauts, 

honestly i have not the finest strip of glue on this .rst syntax and how to debug them. And it was my first github thing i do either. 
I just copied the thing form the dokuwiki guide and tried to adjust. 
Normally i would have dropt just an email to the uberlab... So i doesn't think that i am able to fix it. 

So i did the laravel installation on the day of writing the guide so i think with the actual uberspace 7 release. 
Here is the Laravel Logo [ https://upload.wikimedia.org/wikipedia/commons/9/9a/Laravel.svg | https://upload.wikimedia.org/wikipedia/commons/9/9a/Laravel.svg ] 

So hopefully someone can fix it and bring this guide to live. 

regards Andreas 


Von: "luto" <notifications@github.com> 
An: "Uberspace/lab" <lab@noreply.github.com> 
CC: "Andreas Friesinger" <a.friesinger@leenux.de>, "Author" <author@noreply.github.com> 
Gesendet: Montag, 1. Februar 2021 16:07:17 
Betreff: Re: [Uberspace/lab] Create guide_laravel.rst (#921) 





@luto requested changes on this pull request. 

Thanks for the submission! There are some oversights, so I don't think the guide would actually work like this. Once these are resolved, I'll have another look and take it for a spin. 


In [ https://github.com/Uberspace/lab/pull/921#discussion_r567886376 | source/guide_laravel.rst ] : 
> @@ -0,0 +1,151 @@

+.. highlight:: console

+

+.. author:: Christian Kantelberg <uberlab@mailbox.org>

+

+.. tag:: lang-php

+.. tag:: web

+

+

+.. sidebar:: Logo

+

+  .. image:: _static/images/laravel-logo.png 


Please add this file or don't reference it. 


In [ https://github.com/Uberspace/lab/pull/921#discussion_r567887514 | source/guide_laravel.rst ] : 
> +

+Laravel is a web application framework with expressive, elegant syntax. We’ve already laid the foundation — freeing you to create without sweating the small things.

+

+----

+

+.. note:: For this guide you should be familiar with the basic concepts of

+

+  * :manual:`PHP <lang-php>`

+  * :manual:`Domains <web-domains>`

+

+

+

+Prerequisites

+=============

+

+We're using :manual:`PHP <lang-php>` in the stable version 7.1: 


PHP 7.1 was removed from uberspace 7 in April 2020, the default version is now 7.3. 


In [ https://github.com/Uberspace/lab/pull/921#discussion_r567888376 | source/guide_laravel.rst ] : 
> +.. highlight:: console

+

+.. author:: Christian Kantelberg <uberlab@mailbox.org>

+

+.. tag:: lang-php

+.. tag:: web

+

+

+.. sidebar:: Logo

+

+  .. image:: _static/images/laravel-logo.png

+      :align: center

+

+##########

+Laravel

+########## 


Please make sure the ### and === lines match the length of the actual title, otherwise this generates warnings during the build. 


In [ https://github.com/Uberspace/lab/pull/921#discussion_r567889043 | source/guide_laravel.rst ] : 
> +

+.. include:: includes/web-domain-list.rst

+

+Installation

+============

+

+Fresh Installation

+======================

+

+``cd`` to your user dir, then get Laravel installer via Composer. Finally create a new project using the installer.

+

+::

+

+ [isabell@stardust ~]$ cd /var/www/virtual/$USER/

+ [isabell@stardust html]$ composer global require "laravel/installer"

+ [isabell@stardust html]$ laravel new <projectname> 


Please make up some project name and use it throughout the guide, e.g. myblog or mysite . 


In [ https://github.com/Uberspace/lab/pull/921#discussion_r567889628 | source/guide_laravel.rst ] : 
> +

+The Laravel project is now in your user folder. But Uberspace serves only the /html folder. 

+The accessible files from Laravel are contained in the project/public folder. Therefore we build a symbilic link.

+You can wether built it for a domain already listed on your uberspace or your default domain $user.uber.space. 

+

+First we rename the old html folder then we create the symbolic link. If you browse now $USER.uber.space you get redirected to /var/www/virtual/$USER/<PROJEKTNAME>/public where your index.php start the application up.

+

+::

+

+ [isabell@stardust ~]$ mv html/ htmlbackup/

+ [isabell@stardust html]$ ln -s /var/www/virtual/$USER/<PROJEKTNAME>/public /var/www/virtual/$USER/html

+

+Adjust the .htaccess file

+======================

+

+The most importend Part is the adjusting of the .htaccess file in your public folder. Laravel brings his file with it but for getting it on uberspace to run we need to add one additional line. 
⬇️ Suggested change 
-The most importend Part is the adjusting of the .htaccess file in your public folder. Laravel brings his file with it but for getting it on uberspace to run we need to add one additional line.

+The most important Part is the adjusting of the .htaccess file in your public folder. Laravel brings his file with it but for getting it on uberspace to run we need to add one additional line. 



In [ https://github.com/Uberspace/lab/pull/921#discussion_r567890360 | source/guide_laravel.rst ] : 
> +======================

+The Database is still empty. We need to create the tables specified by migrations folder by using:

+

+::

+

+[isabell@stardust ~]$ php artisan migrate

+

+

+Update

+======

+Just make a git pull request and use 

+composer install - for checking new dependencies

+php artisan migrate - creating new tables

+

+

+Tested with Laravel 8 , Uberspace 7.2.1.0 


Uberspace 7.2.1 was releases mid-2019. I doubt that you used this version to test your guide. 


In [ https://github.com/Uberspace/lab/pull/921#discussion_r567891728 | source/guide_laravel.rst ] : 
> +

+Set a symbolic link

+======================

+

+The Laravel project is now in your user folder. But Uberspace serves only the /html folder. 

+The accessible files from Laravel are contained in the project/public folder. Therefore we build a symbilic link.

+You can wether built it for a domain already listed on your uberspace or your default domain $user.uber.space. 

+

+First we rename the old html folder then we create the symbolic link. If you browse now $USER.uber.space you get redirected to /var/www/virtual/$USER/<PROJEKTNAME>/public where your index.php start the application up.

+

+::

+

+ [isabell@stardust ~]$ mv html/ htmlbackup/

+ [isabell@stardust html]$ ln -s /var/www/virtual/$USER/<PROJEKTNAME>/public /var/www/virtual/$USER/html

+

+Adjust the .htaccess file 


The code blocks in this section don't seem to render correctly. Do you mind having another look? [ https://deploy-preview-921--uberlab.netlify.app/guide_laravel.html#adjust-the-htaccess-file | https://deploy-preview-921--uberlab.netlify.app/guide_laravel.html#adjust-the-htaccess-file ] 



In [ https://github.com/Uberspace/lab/pull/921#discussion_r567891993 | source/guide_laravel.rst ] : 
> +Adjust the .htaccess file

+======================

+

+The most importend Part is the adjusting of the .htaccess file in your public folder. Laravel brings his file with it but for getting it on uberspace to run we need to add one additional line.

+If you don't make the adjust you will end up with an 500 Internal Server Error. 

+

+In your $user/<projectname>/public/.htaccess

+Add: 

+Options +SymLinksIfOwnerMatch

+Above

+RewriteEngine On

+

+Config

+======

+

+Set Database up 


The code blocks in this section don't seem to render correctly. Do you mind having another look? [ https://deploy-preview-921--uberlab.netlify.app/guide_laravel.html#set-database-up | https://deploy-preview-921--uberlab.netlify.app/guide_laravel.html#set-database-up ] 



In [ https://github.com/Uberspace/lab/pull/921#discussion_r567893667 | source/guide_laravel.rst ] : 
> +Your web domain needs to be setup:

+

+.. include:: includes/web-domain-list.rst

+

+Installation

+============

+

+Fresh Installation

+======================

+

+``cd`` to your user dir, then get Laravel installer via Composer. Finally create a new project using the installer.

+

+::

+

+ [isabell@stardust ~]$ cd /var/www/virtual/$USER/

+ [isabell@stardust html]$ composer global require "laravel/i [...]

2021-02-03 12:10 UTC, DaniW42 commented on source/guide_laravel.rst
> +We're using :manual:`PHP <lang-php>` in the stable version 7.1:
According to the [manual ](https://manual.uberspace.de/lang-php/#standard-version)it is 7.4

2021-02-08 12:21 UTC, luto commented
@afriesinger I see! Do you mind if I close this, start a new laravel guide, lift the instructions from yours and credit you as an author?

2021-02-08 12:49 UTC, afriesinger commented
yeah perfekt. So someone can benefit form it. You dont need mind me as author as i wasn't very successful 


thanks 

Andreas 


Von: "luto" <notifications@github.com> 
An: "Uberspace/lab" <lab@noreply.github.com> 
CC: "Andreas Friesinger" <a.friesinger@leenux.de>, "Mention" <mention@noreply.github.com> 
Gesendet: Montag, 8. Februar 2021 13:21:44 
Betreff: Re: [Uberspace/lab] Create guide_laravel.rst (#921) 





[ https://github.com/afriesinger | @afriesinger ] I see! Do you mind if I close this, start a new laravel guide, lift the instructions from yours and credit you as an author? 

— 
You are receiving this because you were mentioned. 
Reply to this email directly, [ https://github.com/Uberspace/lab/pull/921#issuecomment-775107675 | view it on GitHub ] , or [ https://github.com/notifications/unsubscribe-auth/ASFERRQYCL36TJN5KZQJQGDS57JNRANCNFSM4W2OFDBQ | unsubscribe ] .

2021-02-08 12:54 UTC, luto commented
Thanks!

2021-02-08 12:54 UTC, closed without merging