Added guide for TS3AudioBot
Uberspace/lab pull request #942
Opened 2021-02-27 11:20 UTC by Felix-Franz

Added guide for TS3AudioBot

Refer to #940

2021-03-14 15:23 UTC, luto requested changes
Thanks for the guide! It works well :) I added a few suggestions to fix some typos and make the guide easier to follow. Let me know what you think!

Sorry about the long wait. I was quite busy with internal projects.

2021-03-14 15:23 UTC, luto commented on source/guide_ts3audiobot.rst
> +After the configuration is done the bot will automatically connect to the TeamSpeak3 server.
```suggestion
To configure the bot, start it interactively and input your configuration data (unique TeamSpeak user id, server name, server password, ...).
After the configuration is done, the bot will automatically connect to the TeamSpeak3 server.
```

2021-03-14 15:23 UTC, luto commented on source/guide_ts3audiobot.rst
> +  port = <another port>
Each guide should assume that the target uberspace is empty, so the port will be free and we don't need to handle this case here.
```suggestion
```

2021-03-14 15:23 UTC, luto commented on source/guide_ts3audiobot.rst
> + [isabell@stardust ts3audiobot]$ wget https://github.com/Splamy/TS3AudioBot/releases/latest/download/TS3AudioBot_dotnet_core_3.1.zip
```suggestion
 [isabell@stardust ts3audiobot]$ wget https://github.com/Splamy/TS3AudioBot/releases/latest/download/TS3AudioBot_dotnet_core_3.1.zip
(...)
HTTP request sent, awaiting response... 200 OK
Length: 12161538 (12M) [application/octet-stream]
Saving to: ‘TS3AudioBot_dotnet_core_3.1.zip’

100%[=====================================>] 12,161,538  49.3MB/s   in 0.2s   

2021-03-14 16:09:26 (49.3 MB/s) - ‘TS3AudioBot_dotnet_core_3.1.zip’ saved [12161538/12161538]
```
Let's add some sample output so users know what to expect :)

2021-03-14 15:23 UTC, luto commented on source/guide_ts3audiobot.rst
> + [isabell@stardust ts3audiobot]$ dotnet TS3AudioBot.dll
```suggestion
 :emphasize-lines: 1,10,12,17,19
 
 [isabell@stardust ts3audiobot]$ dotnet TS3AudioBot.dll
 16:10:54.4473| INFO|| [============ TS3AudioBot started =============]
 16:10:54.5198| INFO|| [ Date/Time: Sunday, 14 March 2021 16:10:54
 16:10:54.5302| INFO|| [ Version: 0.11.0/master/c7e44e4d
 16:10:54.5310| INFO|| [ Platform: CentOS Linux 7 (Core) (64bit)
 16:10:54.5315| INFO|| [ Runtime: .NET Core (3.1.13) ServerGC:True GC:SustainedLowLatency
 16:10:54.5343| INFO|| [ Opus: libopus 1.0.2 (x64)
 16:10:54.5346| INFO|| [==============================================]
 16:10:55.2626| WARN|| No permission file found.
 Do you want to set up an admin in the default permission file template? [Y/n] Y
 Please enter an admin uid
 YourAdminUID
 16:11:36.1467| INFO|| Creating new permission file ({"AdminUids":["YourAdminUID"], "OverwriteIfExists":false})
 It seems like there are no bots configured.
 Fill out this quick setup to get started.
 Please enter the ip, domain or nickname (with port; default: 9987) where to connect to:
 1.3.3.7:9987
 Please enter the server password (or leave empty for none):
 SecretTSserverPWifAny
 16:12:41.2601| INFO|| Bot "default" connecting to "1.3.3.7:9987"
 16:12:41.8483| INFO|| Started Webserver on port 58913
```
The interactive mode asks quite a few questions. What do you think about adding sample output like this?

2021-03-14 15:23 UTC, luto commented on source/guide_ts3audiobot.rst
> +Restart the bot to active the new config:
```suggestion
Restart the bot to activate the new config:
```

2021-03-14 15:23 UTC, luto commented on source/guide_ts3audiobot.rst
> +Playing youtube videos is currently not possible.
```suggestion
Youtube Videos
==============

Playing youtube videos is currently not possible.
```
What do you think about starting a new section here?

2021-03-14 15:23 UTC, luto commented on source/guide_ts3audiobot.rst
> +You should now be able to reach the bot on ``https://isabell.uber.space``.
```suggestion
Configure the web server
========================

.. note::

    TS3AudioBot is running on port 58913.

.. include:: includes/web-backend.rst
```
Proxies using `.htaccess` are deprecated on uberspace 7, please use a [web backend](https://manual.uberspace.de/web-backends/) instead.

2021-03-14 15:23 UTC, luto commented on source/guide_ts3audiobot.rst
> + [isabell@stardust ~]$ rm ~/html/.htaccess
Please adapt this for web backends as well.

2021-03-15 15:41 UTC, Felix-Franz commented
Thanks for your suggestions @luto, I have added all of them!

2021-03-15 15:50 UTC, merged

2021-03-15 15:50 UTC, luto commented
Awesome, thank you! :tada: